In [1]:
# import numpy as np
import  matplotlib.pyplot as plt  
import pandas as pd 
 
import warnings
warnings.filterwarnings('ignore')
import seaborn as sns
import os, sys

In [2]:
os.listdir()

['.DS_Store',
 '.ipynb_checkpoints',
 '50_Startups.csv',
 'data_preprocessing_template.py',
 'data_preprocessing_template.R',
 'Multiple_Linear_Regression',
 'multiple_linear_regression.py',
 'multiple_linear_regression.R',
 "P14-Multiple-Linear-Regression.zip; filename=utf-8''P14-Multiple-Linear-Regression(1).zi",
 'Untitled-Copy1.ipynb',
 '__MACOSX']

In [3]:
data1 = pd.read_csv('50_Startups.csv')

In [4]:
data1.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [5]:
data1.tail()

R&D Spend  Administration  Marketing Spend       State    Profit
45    1000.23       124153.04          1903.93    New York  64926.08
46    1315.46       115816.21        297114.46     Florida  49490.75
47       0.00       135426.92             0.00  California  42559.73
48     542.05        51743.15             0.00    New York  35673.41
49       0.00       116983.80         45173.06  California  14681.40

In [6]:
data1.info

<bound method DataFrame.info of     R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida

In [7]:
X = data1.iloc[:, :-1].values

In [8]:
y = data1.iloc[:, 4].values

In [9]:
data1.info

<bound method DataFrame.info of     R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [11]:
X_train

array([[55493.95, 103057.49, 214634.81, 'Florida'],
       [46014.02, 85047.44, 205517.64, 'New York'],
       [75328.87, 144135.98, 134050.07, 'Florida'],
       [46426.07, 157693.92, 210797.67, 'California'],
       [91749.16, 114175.79, 294919.57, 'Florida'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [1000.23, 124153.04, 1903.93, 'New York'],
       [542.05, 51743.15, 0.0, 'New York'],
       [65605.48, 153032.06, 107138.38, 'New York'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [61994.48, 115641.28, 91131.24, 'Florida'],
       [63408.86, 129219.61, 46085.25, 'California'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [23640.93, 96189.63, 148001.11, 'California'],
       [76253.86, 113867.3, 298664.47, 'California'],
       [15505.73, 127382.3, 35534.17, 'New York'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [91992.39, 135495.07, 252664.93, 'California'],
  

In [12]:
X_test

array([[66051.52, 182645.56, 118148.2, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [27892.92, 84710.77, 164470.71, 'Florida'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [72107.6, 127864.55, 353183.81, 'New York'],
       [20229.59, 65947.93, 185265.1, 'New York'],
       [61136.38, 152701.92, 88218.23, 'New York'],
       [73994.56, 122782.75, 303319.26, 'Florida'],
       [142107.34, 91391.77, 366168.42, 'Florida']], dtype=object)

In [13]:
y_train

array([ 96778.92,  96479.51, 105733.54,  96712.8 , 124266.9 , 155752.6 ,
       132602.65,  64926.08,  35673.41, 101004.64, 129917.04,  99937.59,
        97427.84, 126992.93,  71498.49, 118474.03,  69758.98, 152211.77,
       134307.35, 107404.34, 156991.12, 125370.37,  78239.91,  14681.4 ,
       191792.06, 141585.52,  89949.14, 108552.04, 156122.51, 108733.99,
        90708.19, 111313.02, 122776.86, 149759.96,  81005.76,  49490.75,
       182901.99, 192261.83,  42559.73,  65200.33])

In [14]:
y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

In [15]:
#from sklearn.linear_model import LinearRegression#


In [16]:
#regressor = LinearRegression()#

In [17]:
#regressor.fit(X_train, y_train)#

In [18]:
#y_pred = regressor.predict(X_test) #

In [23]:
y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

In [24]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [25]:
labelencoder_X = LabelEncoder()

In [26]:
X[:, 3] = labelencoder_X.fit_transform(X[:, 3])

In [27]:
onehotencoder = OneHotEncoder(categorical_features = [3])

In [28]:
X = onehotencoder.fit_transform(X).toarray()

C:\Users\lydia\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:450: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [29]:
X = X[:, 1:]

In [30]:
from sklearn.linear_model import LinearRegression

In [31]:
regressor = LinearRegression()

In [36]:
y_pred = regressor.predict(X_test)

NotFittedError: This LinearRegression instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.

In [ ]:
y_pred

In [ ]:
y_test

In [ ]:
plt.scatter(X_train, y_train, color = 'purple')
plt.plot(X_train, regressor.predict(X_train), color ='blue') 
plt.title('Salary vs Experience (Training set)') 
plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.show()

In [28]:
import numpy as  np

In [29]:
X = np.append(arr = np.ones((50, 1)).astype(int), values = X, axis = 1 )

In [54]:
X_opt = X[:, [0, 3, 4, 5]]

In [53]:
X_opt   

array([[1, 1, 165349.2, 136897.8, 471784.1],
       [1, 1, 162597.7, 151377.59, 443898.53],
       [1, 1, 153441.51, 101145.55, 407934.54],
       [1, 1, 144372.41, 118671.85, 383199.62],
       [1, 1, 142107.34, 91391.77, 366168.42],
       [1, 1, 131876.9, 99814.71, 362861.36],
       [1, 1, 134615.46, 147198.87, 127716.82],
       [1, 1, 130298.13, 145530.06, 323876.68],
       [1, 1, 120542.52, 148718.95, 311613.29],
       [1, 1, 123334.88, 108679.17, 304981.62],
       [1, 1, 101913.08, 110594.11, 229160.95],
       [1, 1, 100671.96, 91790.61, 249744.55],
       [1, 1, 93863.75, 127320.38, 249839.44],
       [1, 1, 91992.39, 135495.07, 252664.93],
       [1, 1, 119943.24, 156547.42, 256512.92],
       [1, 1, 114523.61, 122616.84, 261776.23],
       [1, 1, 78013.11, 121597.55, 264346.06],
       [1, 1, 94657.16, 145077.58, 282574.31],
       [1, 1, 91749.16, 114175.79, 294919.57],
       [1, 1, 86419.7, 153514.11, 0.0],
       [1, 1, 76253.86, 113867.3, 298664.47],
       [1, 1, 7

In [37]:
import statsmodels.formula.api as sm

In [41]:
from sklearn.linear_model import LinearRegression

In [43]:
regressor = LinearRegression()

In [ ]:
regressor.fit(X_train, y_train)

In [ ]:
y_pred = regressor.predict(X_test)

In [52]:
import statsmodels.formula.api as sm

In [55]:
import numpy as np

In [56]:
X = np.append(arr = np.ones((50, 1)).astype(int), values = X, axis = 1)

In [57]:
X_opt = X[:, [0, 1, 2, 3, 4, 5]]

In [ ]:
regressor_OLS = sm.OLS(endog =y, exog = X_opt).fit()

In [ ]:
regressor_OLS.summary()

In [ ]:
X_opt = [0, 1, 3, 4, 5]

In [ ]:
data1.head

In [ ]:
plt.scatter(X_test, y_test, color = 'blue')
plt.plot(X_train, regressor.predict(X_train), color ='yellow') 
plt.title('Salary vs Experience (Test set)') 
plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.show()